
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxhgjhvbkgloqlaqwzok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4aGdqaHZia2dsb3FsYXF3em9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3Njc1NzgsImV4cCI6MjA1NzM0MzU3OH0.FJXD9uFfKXfFKjMzrHqt0qdtf3nW_8xbzb8Zy0QioEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
